# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forgecli < Formula
  desc "Software to easily install minecraft mod clients and mods"
  homepage ""
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shotah/forgecli/releases/download/1.0.5/forgecli_1.0.5_darwin_arm64.tar.gz"
      sha256 "7f602ed24cc8c0c9d95a9933f9ff762f65724d2a9db1020321a001ded363d062"

      def install
        bin.install "forgecli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shotah/forgecli/releases/download/1.0.5/forgecli_1.0.5_darwin_amd64.tar.gz"
      sha256 "3434884a53ab0f84678d7b671e643a094d9406018873a85319a92d7b306dbe53"

      def install
        bin.install "forgecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shotah/forgecli/releases/download/1.0.5/forgecli_1.0.5_linux_arm64.tar.gz"
      sha256 "dcb23988850435237a05367caa8ef494fa9bb5cdeff9f03f815291c0ae10aebb"

      def install
        bin.install "forgecli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shotah/forgecli/releases/download/1.0.5/forgecli_1.0.5_linux_amd64.tar.gz"
      sha256 "ab928756be11bab82a34fb86b6d88c42b52e10628a2de5d42332ee6f914cd395"

      def install
        bin.install "forgecli"
      end
    end
  end
end
