# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forgecli < Formula
  desc "Software to easily install minecraft mod clients and mods"
  homepage ""
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shotah/forgecli/releases/download/v1.0.4/forgecli_1.0.4_darwin_arm64.tar.gz"
      sha256 "8540431c44f9484d34eccd7c51322037efedc90257b52f1bac581e8f6eeb9f01"

      def install
        bin.install "forgecli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shotah/forgecli/releases/download/v1.0.4/forgecli_1.0.4_darwin_amd64.tar.gz"
      sha256 "fbd00ff43200f046bcad1ef7a5d948f1ea54cc9469e79e59526e96e03c83187d"

      def install
        bin.install "forgecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shotah/forgecli/releases/download/v1.0.4/forgecli_1.0.4_linux_arm64.tar.gz"
      sha256 "7663625fe00131e03d6f7d397cd2165d97b569c715dbd2eea71808dace405296"

      def install
        bin.install "forgecli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shotah/forgecli/releases/download/v1.0.4/forgecli_1.0.4_linux_amd64.tar.gz"
      sha256 "899cfcbda01aa66ee031e36d6cf52b49ca80a787923ad1218cc1e20b1464a914"

      def install
        bin.install "forgecli"
      end
    end
  end
end
