# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forgecli < Formula
  desc "Software to easily install minecraft mod clients and mods"
  homepage ""
  version "1.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shotah/forgecli/releases/download/1.0.9/forgecli_1.0.9_darwin_arm64.tar.gz"
      sha256 "bb09b9da5539b685365b6c085b916d2f6fab51974523a97296cfc8e9da03e2aa"

      def install
        bin.install "forgecli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shotah/forgecli/releases/download/1.0.9/forgecli_1.0.9_darwin_amd64.tar.gz"
      sha256 "125de849744ea757fd8811c392eaea74004039b66f5fbf33d0da8675178ba2e5"

      def install
        bin.install "forgecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shotah/forgecli/releases/download/1.0.9/forgecli_1.0.9_linux_amd64.tar.gz"
      sha256 "6963021be9737c8dc321725431e95a4a07e3f633e232f6c6e457066ba6d2cc2e"

      def install
        bin.install "forgecli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shotah/forgecli/releases/download/1.0.9/forgecli_1.0.9_linux_arm64.tar.gz"
      sha256 "7cbdb56cd5b50c5a3bdc6ed8186dba2e79d33a6ac1b59d206c562f0d1d867845"

      def install
        bin.install "forgecli"
      end
    end
  end
end
